services:
  backend:
    build: 
      context: ./backend
    container_name: php-app
    working_dir: /var/www
    volumes:
      - "./backend/src:/var/www/html"
      - "./backend/apache2/apache2.conf:/etc/apache2/apache2.conf"
      - "./backend/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    ports:
      - "8000:80"
    depends_on:
      - database
    networks:
      - postgres_network

  
  frontend:
    build: 
      context: ./frontend
    container_name: react-app
    volumes:
      - ./frontend:/app:cached
      - react_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - postgres_network
    environment:
      - WATCHPACK_POLLING=true

  database:
    container_name: postgres-db
    restart: always
    build:
      context: .
      dockerfile: postgres/Dockerfile
    platform: linux/x86_64
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    # ヘルスチェック
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
    networks:
      - postgres_network

volumes:
  database:
  react_node_modules:

networks:
  postgres_network:
    driver: bridge