services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php
    volumes:
      - ./php:/var/www/html
    networks:
      - app-network

  # nginx:
  #   build: 
  #     context: .
  #     dockerfile: nginx/Dockerfile
  #   container_name: nginx
  #   volumes:
  #     - ./php:/var/www/html
  #     - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
  #     - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - app-network

  postgres:
    image: postgres:latest
    container_name: pgsql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: equipment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  node:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    container_name: node
    tty: true
    volumes:
      - ./frontend:/app
      - /frontend/frontend/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
