services:
  backend:
    build: 
      context: ./backend
    container_name: php-app
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=equipment_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
  
  frontend:
    build: 
      context: ./frontend
    container_name: react-app
    tty: true
    volumes:
      - ./frontend:/app
      - /frontend/frontend/node_modules
    ports:
      - "3000:3000"
    # networks:
    #   - app-network

  database:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: equipment_db
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  database:
