version: '3.8'

services:
  php:
    build:
      context: ./php
    volumes:
      - ./php:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./php:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: equipment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  react:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
